[build]
  command = "NODE_ENV=production gatsby build"
  publish = "public/"

[build.environment]
  YARN_VERSION = "1.4.0"

[template]
  incoming-hooks = ["Ghost"]

[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
  public, 
  max-age=604800,
	immutable'''
